repo_url: https://github.com/NiallOswald/clapeyron-jax
repo_name: NiallOswald/clapeyron-jax

strict: true

theme:
  features:
    - navigation.sections
    - toc.integrate
    - header.autohide
  icon:
    repo: fontawesome/brands/github  # GitHub logo in top right

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: "¤"
      toc_depth: 4

plugins:
  - hippogriffe:
      extra_public_objects:
        - jax.Array

nav:
  - 'index.md'
  - API:
    - 'reference/wrapper.md'
