[project]
name = "clapeyron-jax"
dynamic = ["version"]
description = "JAX-compatible bindings for Clapeyron.jl."
readme = "README.md"
authors = [
    { name = "Niall Oswald", email = "niall.oswald@hotmail.co.uk" }
]
requires-python = ">=3.12"
dependencies = [
    "equinox>=0.13.4",
    "jax>=0.9.1",
    "jaxtyping>=0.3.9",
    "juliacall>=0.9.31",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "juliapkg>=0.1.23",
]
docs = [
    "hippogriffe>=0.2.2",
    "zensical>=0.0.46",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
bump = true
